# Generated by Django 5.1.1 on 2024-09-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbe',
            name='binomial_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='microbe',
            name='ncbi_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
