# Generated by Django 5.1.1 on 2024-09-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundTruthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binomial_name', models.CharField(max_length=255, unique=True)),
                ('ncbi_id', models.IntegerField()),
                ('motility', models.BooleanField()),
                ('gram_staining', models.CharField(max_length=50)),
                ('aerophilicity', models.CharField(blank=True, max_length=50, null=True)),
                ('extreme_environment_tolerance', models.BooleanField(blank=True, null=True)),
                ('biofilm_formation', models.BooleanField(blank=True, null=True)),
                ('animal_pathogenicity', models.BooleanField(blank=True, null=True)),
                ('biosafety_level', models.CharField(max_length=50)),
                ('health_association', models.BooleanField(blank=True, null=True)),
                ('host_association', models.BooleanField(blank=True, null=True)),
                ('plant_pathogenicity', models.BooleanField(blank=True, null=True)),
                ('spore_formation', models.BooleanField(blank=True, null=True)),
                ('hemolysis', models.BooleanField(blank=True, null=True)),
                ('cell_shape', models.CharField(max_length=50)),
                ('member_of_wa_subset', models.BooleanField()),
                ('superkingdom', models.CharField(max_length=50)),
                ('phylum', models.CharField(max_length=50)),
                ('class_field', models.CharField(max_length=50)),
                ('order', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('genus', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('ftp_path', models.URLField(blank=True, null=True)),
                ('fasta_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
