# Generated by Django 5.1.1 on 2024-09-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0002_groundtruthdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binomial_name', models.CharField(max_length=200, unique=True)),
                ('ncbi_id', models.IntegerField()),
                ('alternative_names', models.JSONField(default=list)),
                ('ftp_path', models.CharField(blank=True, max_length=500, null=True)),
                ('fasta_file', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('microbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonl_viewer.microbe')),
            ],
        ),
        migrations.CreateModel(
            name='PhenotypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(max_length=50)),
                ('allowed_values', models.JSONField(default=list)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superkingdom', models.CharField(max_length=100)),
                ('phylum', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='GroundTruthData',
        ),
        migrations.DeleteModel(
            name='JSONLEntry',
        ),
        migrations.AddField(
            model_name='phenotype',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonl_viewer.phenotypedefinition'),
        ),
        migrations.AddField(
            model_name='microbe',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonl_viewer.taxonomy'),
        ),
    ]
