# Generated by Django 5.1.1 on 2024-09-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0004_modelranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelranking',
            name='balanced_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelranking',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
