# Generated by Django 5.1.1 on 2024-09-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0006_alter_phenotype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotype',
            name='value',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='MicrobeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('model', models.CharField(max_length=100)),
                ('inference_date_time', models.DateTimeField(auto_now_add=True)),
                ('microbe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='jsonl_viewer.microbe')),
            ],
        ),
    ]
