# Generated by Django 5.1.1 on 2024-09-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0009_delete_microbedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrobeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_type', models.CharField(choices=[('general', 'General'), ('biomes', 'Biomes'), ('habitats', 'Habitats')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('inference_date_time', models.DateTimeField(auto_now=True)),
                ('microbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='jsonl_viewer.microbe')),
            ],
            options={
                'unique_together': {('microbe', 'description_type', 'model')},
            },
        ),
    ]
