# Generated by Django 5.1.1 on 2024-09-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0011_alter_microbedescription_description_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbe',
            name='binomial_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('microbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='jsonl_viewer.microbe')),
            ],
        ),
    ]
