# Generated by Django 5.1.1 on 2024-10-28 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0012_alter_microbe_binomial_name_errorreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='microbe',
            name='access_count_tools',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='microbe',
            name='access_count_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MicrobeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('search_tool', models.CharField(blank=True, max_length=255, null=True)),
                ('microbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='jsonl_viewer.microbe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starred_microbes', models.ManyToManyField(blank=True, related_name='starred_by', to='jsonl_viewer.microbe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
