# Generated by Django 5.1.1 on 2024-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0014_profile_institute_microberequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbedescription',
            name='change_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='microbedescription',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
