# Generated by Django 5.1.1 on 2024-11-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0015_microbedescription_change_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhenotypeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majority_value', models.CharField(default='N/A', max_length=255)),
                ('agreement_percentage', models.PositiveIntegerField(default=0)),
                ('supporting_models', models.PositiveIntegerField(default=0)),
                ('total_models', models.PositiveIntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonl_viewer.phenotypedefinition')),
                ('microbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenotype_summaries', to='jsonl_viewer.microbe')),
            ],
            options={
                'unique_together': {('microbe', 'definition')},
            },
        ),
    ]
