# Generated by Django 5.1.1 on 2024-11-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonl_viewer', '0016_phenotypesummary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='phenotypesummary',
            index=models.Index(fields=['microbe', 'definition'], name='jsonl_viewe_microbe_4e9510_idx'),
        ),
        migrations.AddIndex(
            model_name='phenotypesummary',
            index=models.Index(fields=['majority_value'], name='jsonl_viewe_majorit_108701_idx'),
        ),
    ]
